version: '3'
services:
  mongodb:
    image: mongo
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
     - 27017:27017
    volumes:
      - type: bind
        source: ./data
        target: /data/db
